# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package' # Optional
    
    - task: Docker@2
      displayName: Build an eureka
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/eureka/Dockerfile'
        tags: |
          $(tag)
          
    - task: Docker@2
      displayName: Build an location
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/location/Dockerfile'
        tags: |
          $(tag)
          
          
    - task: Docker@2
      displayName: Build an weather
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/weather/Dockerfile'
        tags: |
          $(tag)
          
   
    - task: Docker@2
      displayName: Build an Cache
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/cache/Dockerfile'
        tags: |
          $(tag)
          
          
    - task: Docker@2
      displayName: Build an zuul
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/zuul/Dockerfile'
        tags: |
          $(tag)
          
    - task: Docker@2
      displayName: Build an web
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/web/Dockerfile'
        tags: |
          $(tag)
          